"""
RAAH Milestone 13 Phase 4 Acceptance Test Suite
===============================================
M13.3 Phase 2 — Decision Explanation API Validation:
1. Real dispatch creates evidence
2. Retrieve that evidence by ID
3. Returned evidence matches the recorder's actual evidence
4. Returned explanation is generated by the deterministic formatter
5. Repeated GET requests return identical explanation
6. Incident lookup returns the correct evidence records
7. Incident records have deterministic ordering
8. Unknown evidence ID returns 404
9. Incident with no evidence behaves correctly
10. Unauthenticated request returns 401
11. Authorized operator can read evidence
12. Unauthorized role is rejected if applicable (403)
13. Response contains no secrets/tokens/internal paths
14. API is strictly read-only
15. GET requests do not mutate DispatchState
16. Recent evidence endpoint works correctly
17. Explanation API latency is lightweight (<15ms)
18. Alternatives are exposed honestly without fabrication
19. Redirection and optimization evidence retrieved accurately
"""

import copy
import json
import os
import sys
import time
import unittest
from datetime import timedelta
from unittest.mock import patch

# Ensure root is in sys.path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from fastapi.testclient import TestClient
from api.main import app
from api.dependencies import manager
from api.settings import settings
from api.auth import (
    create_test_token,
    Role,
    Permission,
    PERMISSION_ROLES,
    AuthenticatedUser,
)
from api.auth.dependencies import get_current_user
from api.decision_evidence import (
    evidence_store,
    DecisionType,
    ConstraintEvaluation,
    CandidateAlternative,
    DecisionEvidenceRecord,
    format_explanation,
)


class TestM13Phase4(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(app)
        manager.initialize()
        cls.admin_token = create_test_token(role=Role.ADMINISTRATOR, username="admin_user")
        cls.dispatcher_token = create_test_token(role=Role.DISPATCHER, username="disp_user")
        cls.supervisor_token = create_test_token(role=Role.SUPERVISOR, username="sup_user")
        cls.medctrl_token = create_test_token(role=Role.MEDICAL_CONTROLLER, username="med_user")
        cls.headers = {"Authorization": f"Bearer {cls.dispatcher_token}"}

    def setUp(self):
        manager.reset()
        evidence_store.clear()
        app.dependency_overrides.clear()

    def tearDown(self):
        app.dependency_overrides.clear()

    # -----------------------------------------------------------------
    # 1. Real dispatch creates evidence
    # -----------------------------------------------------------------
    def test_01_real_dispatch_creates_evidence(self):
        """Authoritative POST /dispatch/1 must record structured evidence in evidence_store."""
        resp = self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        self.assertEqual(resp.status_code, 200)

        records = evidence_store.get_by_incident(1)
        self.assertGreaterEqual(len(records), 1)
        rec = records[-1]
        self.assertEqual(rec.incident_id, 1)
        self.assertEqual(rec.decision_type, DecisionType.INITIAL_DISPATCH)
        self.assertIsNotNone(rec.evidence_id)

    # -----------------------------------------------------------------
    # 2. Retrieve that evidence by ID
    # -----------------------------------------------------------------
    def test_02_retrieve_evidence_by_id(self):
        """GET /decision-evidence/{evidence_id} retrieves the structured record and explanation."""
        # Create evidence via dispatch
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        records = evidence_store.get_by_incident(1)
        rec = records[0]

        resp = self.client.get(f"/decision-evidence/{rec.evidence_id}", headers=self.headers)
        self.assertEqual(resp.status_code, 200)
        data = resp.json()

        self.assertIn("evidence", data)
        self.assertIn("explanation", data)
        self.assertEqual(data["evidence"]["evidence_id"], rec.evidence_id)
        self.assertEqual(data["evidence"]["decision_type"], "INITIAL_DISPATCH")
        self.assertIsInstance(data["explanation"], str)
        self.assertGreater(len(data["explanation"]), 0)

    # -----------------------------------------------------------------
    # 3. Returned evidence matches the recorder's actual evidence
    # -----------------------------------------------------------------
    def test_03_returned_evidence_matches_recorder_evidence(self):
        """Returned evidence model must match the authoritative stored record."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        store_rec = evidence_store.get_by_incident(1)[0]

        resp = self.client.get(f"/decision-evidence/{store_rec.evidence_id}", headers=self.headers)
        self.assertEqual(resp.status_code, 200)
        evidence_data = resp.json()["evidence"]

        self.assertEqual(evidence_data["evidence_id"], store_rec.evidence_id)
        self.assertEqual(evidence_data["decision_type"], store_rec.decision_type.value)
        self.assertEqual(evidence_data["action"], store_rec.action)
        self.assertEqual(evidence_data["incident_id"], store_rec.incident_id)
        self.assertEqual(evidence_data["sim_time"], store_rec.sim_time)
        self.assertEqual(evidence_data["severity"], store_rec.severity)
        self.assertEqual(evidence_data["priority"], store_rec.priority)
        self.assertEqual(evidence_data["selected_ambulance_id"], store_rec.selected_ambulance_id)
        self.assertEqual(evidence_data["selected_hospital_id"], store_rec.selected_hospital_id)
        self.assertEqual(evidence_data["alternatives_available"], store_rec.alternatives_available)

    # -----------------------------------------------------------------
    # 4. Returned explanation is generated by the deterministic formatter
    # -----------------------------------------------------------------
    def test_04_returned_explanation_matches_deterministic_formatter(self):
        """Explanation string returned by API must strictly match format_explanation(record)."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        store_rec = evidence_store.get_by_incident(1)[0]
        expected_explanation = format_explanation(store_rec)

        resp = self.client.get(f"/decision-evidence/{store_rec.evidence_id}", headers=self.headers)
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()["explanation"], expected_explanation)

    # -----------------------------------------------------------------
    # 5. Repeated GET requests return identical explanation
    # -----------------------------------------------------------------
    def test_05_repeated_get_returns_identical_explanation(self):
        """Repeated GET requests for same evidence ID must return byte-for-byte identical explanations."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        store_rec = evidence_store.get_by_incident(1)[0]

        first_resp = self.client.get(f"/decision-evidence/{store_rec.evidence_id}", headers=self.headers)
        first_json = first_resp.json()

        for _ in range(25):
            r = self.client.get(f"/decision-evidence/{store_rec.evidence_id}", headers=self.headers)
            self.assertEqual(r.status_code, 200)
            self.assertEqual(r.json()["explanation"], first_json["explanation"])
            self.assertEqual(r.json()["evidence"], first_json["evidence"])

    # -----------------------------------------------------------------
    # 6. Incident lookup returns the correct evidence records
    # -----------------------------------------------------------------
    def test_06_incident_lookup_returns_correct_records(self):
        """GET /decision-evidence/incident/{incident_id} returns all records for that incident."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        self.client.post("/dispatch/2", headers={"Authorization": f"Bearer {self.admin_token}"})

        resp_inc1 = self.client.get("/decision-evidence/incident/1", headers=self.headers)
        self.assertEqual(resp_inc1.status_code, 200)
        data1 = resp_inc1.json()
        self.assertEqual(data1["incident_id"], 1)
        self.assertGreaterEqual(len(data1["records"]), 1)
        for item in data1["records"]:
            self.assertEqual(item["evidence"]["incident_id"], 1)

        resp_inc2 = self.client.get("/decision-evidence/incident/2", headers=self.headers)
        self.assertEqual(resp_inc2.status_code, 200)
        data2 = resp_inc2.json()
        self.assertEqual(data2["incident_id"], 2)
        self.assertGreaterEqual(len(data2["records"]), 1)
        for item in data2["records"]:
            self.assertEqual(item["evidence"]["incident_id"], 2)

    # -----------------------------------------------------------------
    # 7. Incident records have deterministic ordering
    # -----------------------------------------------------------------
    def test_07_incident_records_deterministic_ordering(self):
        """Incident records must be returned in deterministic chronological order."""
        rec1 = DecisionEvidenceRecord(
            decision_type=DecisionType.INITIAL_DISPATCH,
            action="DISPATCH_1",
            incident_id=42,
            sim_time=100,
            timestamp_iso="2026-09-07T10:00:00+00:00",
        )
        rec2 = DecisionEvidenceRecord(
            decision_type=DecisionType.HOSPITAL_REDIRECTION,
            action="REDIRECT_1",
            incident_id=42,
            sim_time=150,
            timestamp_iso="2026-09-07T10:05:00+00:00",
        )
        rec3 = DecisionEvidenceRecord(
            decision_type=DecisionType.INITIAL_DISPATCH,
            action="DISPATCH_PRE",
            incident_id=42,
            sim_time=50,
            timestamp_iso="2026-09-07T09:55:00+00:00",
        )

        # Record out of order
        evidence_store.record(rec1)
        evidence_store.record(rec2)
        evidence_store.record(rec3)

        resp = self.client.get("/decision-evidence/incident/42", headers=self.headers)
        self.assertEqual(resp.status_code, 200)
        records = resp.json()["records"]
        self.assertEqual(len(records), 3)

        sim_times = [r["evidence"]["sim_time"] for r in records]
        self.assertEqual(sim_times, [50, 100, 150], "Must sort chronologically by sim_time")

    # -----------------------------------------------------------------
    # 8. Unknown evidence ID returns 404
    # -----------------------------------------------------------------
    def test_08_unknown_evidence_id_returns_404(self):
        """GET /decision-evidence/{unknown_id} returns HTTP 404 with standardized error JSON."""
        resp = self.client.get("/decision-evidence/non-existent-uuid-9999", headers=self.headers)
        self.assertEqual(resp.status_code, 404)
        data = resp.json()
        self.assertIn("error", data)
        self.assertIn("detail", data)
        self.assertIn("not found", data["detail"].lower())

    # -----------------------------------------------------------------
    # 9. Incident with no evidence behaves correctly
    # -----------------------------------------------------------------
    def test_09_incident_with_no_evidence_returns_clean_empty_records(self):
        """Valid incident with no records returns HTTP 200 with records: []."""
        resp = self.client.get("/decision-evidence/incident/987654", headers=self.headers)
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assertEqual(data["incident_id"], 987654)
        self.assertEqual(data["records"], [])

    # -----------------------------------------------------------------
    # 10. Unauthenticated request returns 401
    # -----------------------------------------------------------------
    def test_10_unauthenticated_request_returns_401(self):
        """Missing or malformed authorization credentials must return HTTP 401."""
        prev_fallback = settings.dev_auth_fallback
        try:
            settings.dev_auth_fallback = False
            # 1. Missing token
            r_missing = self.client.get("/decision-evidence/incident/1")
            self.assertEqual(r_missing.status_code, 401)
            self.assertIn("WWW-Authenticate", r_missing.headers)

            # 2. Malformed token
            r_malformed = self.client.get(
                "/decision-evidence/incident/1",
                headers={"Authorization": "Bearer invalid-garbage-token"},
            )
            self.assertEqual(r_malformed.status_code, 401)

            # 3. Invalid signature
            fake_sig_token = create_test_token(
                role=Role.DISPATCHER,
                secret_key="some-different-secret-key-that-is-at-least-32-chars",
            )
            r_bad_sig = self.client.get(
                "/decision-evidence/incident/1",
                headers={"Authorization": f"Bearer {fake_sig_token}"},
            )
            self.assertEqual(r_bad_sig.status_code, 401)

            # 4. Expired token
            expired_token = create_test_token(
                role=Role.DISPATCHER,
                expires_delta=timedelta(seconds=-60),
            )
            r_exp = self.client.get(
                "/decision-evidence/incident/1",
                headers={"Authorization": f"Bearer {expired_token}"},
            )
            self.assertEqual(r_exp.status_code, 401)
        finally:
            settings.dev_auth_fallback = prev_fallback

    # -----------------------------------------------------------------
    # 11. Authorized operator can read evidence
    # -----------------------------------------------------------------
    def test_11_authorized_operator_can_read_evidence(self):
        """All authorized operational roles with VIEW_LIVE can read decision evidence."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        rec = evidence_store.get_by_incident(1)[0]

        roles_to_test = [
            (Role.DISPATCHER, self.dispatcher_token),
            (Role.SUPERVISOR, self.supervisor_token),
            (Role.MEDICAL_CONTROLLER, self.medctrl_token),
            (Role.ADMINISTRATOR, self.admin_token),
        ]

        for role, token in roles_to_test:
            resp = self.client.get(
                f"/decision-evidence/{rec.evidence_id}",
                headers={"Authorization": f"Bearer {token}"},
            )
            self.assertEqual(
                resp.status_code,
                200,
                f"Role {role.value} with VIEW_LIVE permission should be allowed (got {resp.status_code})",
            )

    # -----------------------------------------------------------------
    # 12. Unauthorized role is rejected if applicable (403)
    # -----------------------------------------------------------------
    def test_12_unauthorized_role_rejected_403(self):
        """When an authenticated user lacks the required permission, endpoint returns 403."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        rec = evidence_store.get_by_incident(1)[0]

        import api.auth.models
        with patch.dict(api.auth.models.PERMISSION_ROLES, {Permission.VIEW_LIVE: {Role.ADMINISTRATOR}}):
            # Dispatcher should now receive 403 Forbidden
            resp = self.client.get(
                f"/decision-evidence/{rec.evidence_id}",
                headers={"Authorization": f"Bearer {self.dispatcher_token}"},
            )
            self.assertEqual(resp.status_code, 403)
            data = resp.json()
            self.assertIn("Forbidden", data.get("detail", ""))

            # Administrator should still succeed with 200
            resp_admin = self.client.get(
                f"/decision-evidence/{rec.evidence_id}",
                headers={"Authorization": f"Bearer {self.admin_token}"},
            )
            self.assertEqual(resp_admin.status_code, 200)

    # -----------------------------------------------------------------
    # 13. Response contains no secrets/tokens/internal paths
    # -----------------------------------------------------------------
    def test_13_response_contains_no_secrets_or_internal_paths(self):
        """Response payloads must never leak secret keys, tokens, or local file paths."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        rec = evidence_store.get_by_incident(1)[0]

        resp = self.client.get(f"/decision-evidence/{rec.evidence_id}", headers=self.headers)
        raw_text = resp.text

        # Must not contain secret strings or private tokens
        self.assertNotIn(settings.jwt_secret_key, raw_text)
        self.assertNotIn("Bearer", raw_text)
        self.assertNotIn("/home/", raw_text)
        self.assertNotIn("\\home\\", raw_text)
        self.assertNotIn("Traceback", raw_text)

        # Also check error responses (404)
        r404 = self.client.get("/decision-evidence/bad-id-12345", headers=self.headers)
        self.assertNotIn("/home/", r404.text)
        self.assertNotIn("Traceback", r404.text)

    # -----------------------------------------------------------------
    # 14. API is strictly read-only
    # -----------------------------------------------------------------
    def test_14_api_is_strictly_read_only(self):
        """GET calls to the explanation API must not add, remove, or mutate stored evidence."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        rec = evidence_store.get_by_incident(1)[0]

        count_before = len(evidence_store._records)
        buffer_len_before = len(evidence_store._buffer)

        # Make multiple read requests across endpoints
        self.client.get(f"/decision-evidence/{rec.evidence_id}", headers=self.headers)
        self.client.get("/decision-evidence/incident/1", headers=self.headers)
        self.client.get("/decision-evidence/recent", headers=self.headers)
        self.client.get("/decision-evidence/nonexistent", headers=self.headers)

        self.assertEqual(len(evidence_store._records), count_before)
        self.assertEqual(len(evidence_store._buffer), buffer_len_before)

    # -----------------------------------------------------------------
    # 15. GET requests do not mutate DispatchState
    # -----------------------------------------------------------------
    def test_15_get_requests_do_not_mutate_dispatch_state(self):
        """GET calls to the explanation API must not mutate simulation state."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        rec = evidence_store.get_by_incident(1)[0]

        sim_state = manager.simulator.state
        time_before = sim_state.current_time
        amb_count_before = len(sim_state.ambulances)
        inc_count_before = len(sim_state.incidents)
        hosp_count_before = len(sim_state.hospitals)

        # Perform multiple evidence API requests
        for _ in range(10):
            self.client.get(f"/decision-evidence/{rec.evidence_id}", headers=self.headers)
            self.client.get("/decision-evidence/incident/1", headers=self.headers)
            self.client.get("/decision-evidence/recent", headers=self.headers)

        self.assertEqual(sim_state.current_time, time_before)
        self.assertEqual(len(sim_state.ambulances), amb_count_before)
        self.assertEqual(len(sim_state.incidents), inc_count_before)
        self.assertEqual(len(sim_state.hospitals), hosp_count_before)

    # -----------------------------------------------------------------
    # 16. Recent evidence endpoint works correctly
    # -----------------------------------------------------------------
    def test_16_recent_evidence_endpoint(self):
        """GET /decision-evidence/recent returns recent records and counts."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        self.client.post("/dispatch/2", headers={"Authorization": f"Bearer {self.admin_token}"})

        resp = self.client.get("/decision-evidence/recent?limit=10", headers=self.headers)
        self.assertEqual(resp.status_code, 200)
        data = resp.json()

        self.assertIn("count", data)
        self.assertIn("records", data)
        self.assertEqual(data["count"], len(data["records"]))
        self.assertGreaterEqual(data["count"], 2)

    # -----------------------------------------------------------------
    # 17. Explanation API latency is lightweight (<15ms)
    # -----------------------------------------------------------------
    def test_17_explanation_api_latency_lightweight(self):
        """Explanation API lookups must be lightweight in-memory operations (mean < 15ms)."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        rec = evidence_store.get_by_incident(1)[0]

        # Warmup
        self.client.get(f"/decision-evidence/{rec.evidence_id}", headers=self.headers)

        latencies = []
        for _ in range(50):
            start = time.perf_counter()
            r = self.client.get(f"/decision-evidence/{rec.evidence_id}", headers=self.headers)
            elapsed_ms = (time.perf_counter() - start) * 1000.0
            self.assertEqual(r.status_code, 200)
            latencies.append(elapsed_ms)

        mean_latency = sum(latencies) / len(latencies)
        print(f"\nDecision Evidence API mean latency: {mean_latency:.2f} ms (p95: {sorted(latencies)[int(0.95 * len(latencies))]:.2f} ms)")
        self.assertLess(mean_latency, 15.0, f"Mean latency {mean_latency:.2f}ms exceeds 15ms target")

    # -----------------------------------------------------------------
    # 18. Alternatives are exposed honestly without fabrication
    # -----------------------------------------------------------------
    def test_18_alternatives_exposed_honestly(self):
        """API must expose alternatives_available=False honestly when discarded candidates unavailable."""
        self.client.post("/dispatch/1", headers={"Authorization": f"Bearer {self.admin_token}"})
        rec = evidence_store.get_by_incident(1)[0]

        resp = self.client.get(f"/decision-evidence/{rec.evidence_id}", headers=self.headers)
        data = resp.json()

        self.assertFalse(data["evidence"]["alternatives_available"])
        self.assertEqual(data["evidence"]["alternatives"], [])
        self.assertIn("[UNAVAILABLE]", data["explanation"])

    # -----------------------------------------------------------------
    # 19. Redirection and optimization evidence retrieved accurately
    # -----------------------------------------------------------------
    def test_19_redirection_and_optimization_evidence_via_api(self):
        """Evidence for redirection and fleet optimization retrieved accurately via API."""
        # Record redirection
        redir_payload = {
            "incident_id": 99,
            "original_hospital": "HOSP_01",
            "new_hospital": "HOSP_05",
            "eta_before": 18.0,
            "eta_after": 9.5,
            "eta_saved": 8.5,
            "eta_improvement_percent": 47.2,
            "reason": "Trauma team available",
            "severity": "Critical",
            "ambulance_id": "AMB_010",
            "decision": "REDIRECT_EXECUTED",
        }
        redir_rec = evidence_store.record_redirection(redir_payload, sim_time=300)
        self.assertIsNotNone(redir_rec)

        # Query via API
        resp_r = self.client.get(f"/decision-evidence/{redir_rec.evidence_id}", headers=self.headers)
        self.assertEqual(resp_r.status_code, 200)
        data_r = resp_r.json()
        self.assertEqual(data_r["evidence"]["decision_type"], "HOSPITAL_REDIRECTION")
        self.assertIn("HOSP_01", data_r["explanation"])
        self.assertIn("HOSP_05", data_r["explanation"])


if __name__ == "__main__":
    unittest.main()
